void init_MarkDownCGrammar( AbstractParseTree& root )
{   /* Generated by IParse version 1.7 of February 17, 2021. */
    AbstractParseTree tt[100];
    int v = 0;

#define NONE tt[v-1].appendChild(AbstractParseTree());
#define ID(I) tt[v-1].appendChild(Ident(I));
#define VAL(V) tt[v-1].appendChild(V);
#define TREE(N) tt[v++].createTree(N);
#define LIST tt[v++].createList();
#define CLOSE if (--v > 0) tt[v-1].appendChild(tt[v]);

    LIST TREE("nt_def") ID("primary_expr") 
  	LIST TREE("rule") LIST TREE("identalone") CLOSE CLOSE 
    	NONE CLOSE 
   	TREE("rule") LIST ID("int") CLOSE 
    	NONE CLOSE 
   	TREE("rule") LIST ID("double") CLOSE 
    	NONE CLOSE 
   	TREE("rule") LIST ID("char") CLOSE 
    	NONE CLOSE 
   	TREE("rule") LIST ID("string") CLOSE 
    	NONE CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("(") 
      	NONE CLOSE 
     	ID("expr") 
     	TREE("literal") VAL(")") 
      	NONE CLOSE CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("postfix_expr") 
  	LIST TREE("rule") LIST ID("postfix_expr") 
     	TREE("literal") VAL("[") 
      	NONE CLOSE 
     	ID("expr") 
     	TREE("literal") VAL("]") 
      	NONE CLOSE CLOSE 
    	ID("arrayexp") CLOSE 
   	TREE("rule") LIST ID("postfix_expr") 
     	TREE("literal") VAL("(") 
      	NONE CLOSE 
     	TREE("opt") TREE("list") ID("assignment_expr") 
       	NONE CLOSE 
      	NONE CLOSE 
     	TREE("literal") VAL(")") 
      	NONE CLOSE CLOSE 
    	ID("call") CLOSE 
   	TREE("rule") LIST ID("postfix_expr") 
     	TREE("literal") VAL(".") 
      	NONE CLOSE 
     	TREE("identalone") CLOSE CLOSE 
    	ID("field") CLOSE 
   	TREE("rule") LIST ID("postfix_expr") 
     	TREE("literal") VAL("->") 
      	NONE CLOSE 
     	TREE("identalone") CLOSE CLOSE 
    	ID("fieldderef") CLOSE 
   	TREE("rule") LIST ID("postfix_expr") 
     	TREE("literal") VAL("++") 
      	NONE CLOSE CLOSE 
    	ID("post_inc") CLOSE 
   	TREE("rule") LIST ID("postfix_expr") 
     	TREE("literal") VAL("--") 
      	NONE CLOSE CLOSE 
    	ID("post_dec") CLOSE 
   	TREE("rule") LIST ID("macro_ident") 
     	TREE("literal") VAL("(") 
      	NONE CLOSE 
     	TREE("opt") TREE("list") LIST TREE("rule") LIST ID("assignment_expr") CLOSE 
         	NONE CLOSE 
        	TREE("rule") LIST ID("type_specifier") CLOSE 
         	NONE CLOSE CLOSE 
       	NONE CLOSE 
      	NONE CLOSE 
     	TREE("literal") VAL(")") 
      	NONE CLOSE CLOSE 
    	ID("macrocall") CLOSE 
   	TREE("rule") LIST ID("primary_expr") CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("unary_expr") 
  	LIST TREE("rule") LIST TREE("literal") VAL("++") 
      	NONE CLOSE 
     	ID("unary_expr") CLOSE 
    	ID("pre_inc") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("--") 
      	NONE CLOSE 
     	ID("unary_expr") CLOSE 
    	ID("pre_dec") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("&") 
      	NONE CLOSE 
     	ID("cast_expr") CLOSE 
    	ID("address_of") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("*") 
      	NONE CLOSE 
     	ID("cast_expr") CLOSE 
    	ID("deref") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("+") 
      	NONE CLOSE 
     	ID("cast_expr") CLOSE 
    	ID("plus") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("-") 
      	NONE CLOSE 
     	ID("cast_expr") CLOSE 
    	ID("min") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("~") 
      	NONE CLOSE 
     	ID("cast_expr") CLOSE 
    	ID("invert") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("!") 
      	NONE CLOSE 
     	ID("cast_expr") CLOSE 
    	ID("not") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("sizeof") 
      	NONE CLOSE 
     	LIST TREE("rule") LIST ID("unary_expr") CLOSE 
       	ID("typeof") CLOSE 
      	TREE("rule") LIST TREE("literal") VAL("(") 
         	NONE CLOSE 
        	TREE("identalone") CLOSE 
        	TREE("literal") VAL(")") 
         	NONE CLOSE CLOSE 
       	NONE CLOSE CLOSE CLOSE 
    	ID("sizeof") CLOSE 
   	TREE("rule") LIST ID("postfix_expr") CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("cast_expr") 
  	LIST TREE("rule") LIST TREE("literal") VAL("(") 
      	NONE CLOSE 
     	ID("abstract_declaration") 
     	TREE("literal") VAL(")") 
      	NONE CLOSE 
     	ID("cast_expr") CLOSE 
    	ID("cast") CLOSE 
   	TREE("rule") LIST ID("unary_expr") CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("l_expr1") 
  	LIST TREE("rule") LIST ID("l_expr1") 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL("*") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	ID("cast_expr") CLOSE 
    	ID("times") CLOSE 
   	TREE("rule") LIST ID("l_expr1") 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL("/") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	ID("cast_expr") CLOSE 
    	ID("div") CLOSE 
   	TREE("rule") LIST ID("l_expr1") 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL("%") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	ID("cast_expr") CLOSE 
    	ID("mod") CLOSE 
   	TREE("rule") LIST ID("cast_expr") CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("l_expr2") 
  	LIST TREE("rule") LIST ID("l_expr2") 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL("+") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	ID("l_expr1") CLOSE 
    	ID("add") CLOSE 
   	TREE("rule") LIST ID("l_expr2") 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL("-") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	ID("l_expr1") CLOSE 
    	ID("sub") CLOSE 
   	TREE("rule") LIST ID("l_expr1") CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("l_expr3") 
  	LIST TREE("rule") LIST ID("l_expr3") 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL("<<") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	ID("l_expr2") CLOSE 
    	ID("ls") CLOSE 
   	TREE("rule") LIST ID("l_expr3") 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL(">>") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	ID("l_expr2") CLOSE 
    	ID("rs") CLOSE 
   	TREE("rule") LIST ID("l_expr2") CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("l_expr4") 
  	LIST TREE("rule") LIST ID("l_expr4") 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL("<=") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	ID("l_expr3") CLOSE 
    	ID("le") CLOSE 
   	TREE("rule") LIST ID("l_expr4") 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL(">=") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	ID("l_expr3") CLOSE 
    	ID("ge") CLOSE 
   	TREE("rule") LIST ID("l_expr4") 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL("<") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	ID("l_expr3") CLOSE 
    	ID("lt") CLOSE 
   	TREE("rule") LIST ID("l_expr4") 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL(">") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	ID("l_expr3") CLOSE 
    	ID("gt") CLOSE 
   	TREE("rule") LIST ID("l_expr4") 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL("==") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	ID("l_expr3") CLOSE 
    	ID("eq") CLOSE 
   	TREE("rule") LIST ID("l_expr4") 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL("!=") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	ID("l_expr3") CLOSE 
    	ID("ne") CLOSE 
   	TREE("rule") LIST ID("l_expr3") CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("l_expr5") 
  	LIST TREE("rule") LIST ID("l_expr5") 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL("^") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	ID("l_expr4") CLOSE 
    	ID("bexor") CLOSE 
   	TREE("rule") LIST ID("l_expr4") CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("l_expr6") 
  	LIST TREE("rule") LIST ID("l_expr6") 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL("&") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("notamp") CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	ID("l_expr5") CLOSE 
    	ID("land") CLOSE 
   	TREE("rule") LIST ID("l_expr5") CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("l_expr7") 
  	LIST TREE("rule") LIST ID("l_expr7") 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL("|") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	ID("l_expr6") CLOSE 
    	ID("lor") CLOSE 
   	TREE("rule") LIST ID("l_expr6") CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("l_expr8") 
  	LIST TREE("rule") LIST ID("l_expr8") 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL("&&") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	ID("l_expr7") CLOSE 
    	ID("and") CLOSE 
   	TREE("rule") LIST ID("l_expr7") CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("l_expr9") 
  	LIST TREE("rule") LIST ID("l_expr9") 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL("||") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	ID("l_expr8") CLOSE 
    	ID("or") CLOSE 
   	TREE("rule") LIST ID("l_expr8") CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("conditional_expr") 
  	LIST TREE("rule") LIST ID("l_expr9") 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL("?") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	ID("l_expr9") 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL(":") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	ID("conditional_expr") CLOSE 
    	ID("if_expr") CLOSE 
   	TREE("rule") LIST ID("l_expr9") CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("assignment_expr") 
  	LIST TREE("rule") LIST ID("unary_expr") 
     	TREE("wsterminal") ID("s") CLOSE 
     	ID("assignment_operator") 
     	TREE("wsterminal") ID("s") CLOSE 
     	ID("assignment_expr") CLOSE 
    	ID("assignment") CLOSE 
   	TREE("rule") LIST ID("conditional_expr") CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("assignment_operator") 
  	LIST TREE("rule") LIST TREE("literal") VAL("=") 
      	NONE CLOSE CLOSE 
    	ID("ass") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("*=") 
      	NONE CLOSE CLOSE 
    	ID("times_ass") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("/=") 
      	NONE CLOSE CLOSE 
    	ID("div_ass") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("%=") 
      	NONE CLOSE CLOSE 
    	ID("mod_ass") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("+=") 
      	NONE CLOSE CLOSE 
    	ID("add_ass") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("-=") 
      	NONE CLOSE CLOSE 
    	ID("sub_ass") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("<<=") 
      	NONE CLOSE CLOSE 
    	ID("sl_ass") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL(">>=") 
      	NONE CLOSE CLOSE 
    	ID("sr_ass") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("&=") 
      	NONE CLOSE CLOSE 
    	ID("and_ass") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("|=") 
      	NONE CLOSE CLOSE 
    	ID("or_ass") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("^=") 
      	NONE CLOSE CLOSE 
    	ID("exor_ass") CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("expr") 
  	LIST TREE("rule") LIST TREE("list") ID("assignment_expr") 
      	NONE CLOSE CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("constant_expr") 
  	LIST TREE("rule") LIST ID("conditional_expr") CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("declaration") 
  	LIST TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
     	TREE("opt") TREE("seq") LIST TREE("rule") LIST ID("storage_class_specifier") CLOSE 
         	NONE CLOSE 
        	TREE("rule") LIST ID("simple_type_specifier") CLOSE 
         	NONE CLOSE CLOSE 
       	NONE CLOSE 
      	TREE("nongreedy") CLOSE CLOSE 
     	LIST TREE("rule") LIST TREE("list") LIST TREE("rule") LIST ID("declarator") 
            	TREE("opt") LIST TREE("rule") LIST TREE("wsterminal") ID("s") CLOSE 
                	TREE("literal") VAL("=") 
                 	NONE CLOSE 
                	TREE("wsterminal") ID("s") CLOSE 
                	ID("initializer") CLOSE 
               	NONE CLOSE CLOSE 
             	NONE CLOSE CLOSE 
           	NONE CLOSE CLOSE 
         	NONE CLOSE 
        	TREE("literal") VAL(";") 
         	NONE CLOSE CLOSE 
       	ID("var") CLOSE CLOSE CLOSE 
    	ID("vardecl") CLOSE 
   	TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
     	TREE("opt") TREE("seq") LIST TREE("rule") LIST ID("storage_class_specifier") CLOSE 
         	NONE CLOSE 
        	TREE("rule") LIST ID("type_specifier") CLOSE 
         	NONE CLOSE CLOSE 
       	NONE CLOSE 
      	TREE("nongreedy") CLOSE CLOSE 
     	LIST TREE("rule") LIST ID("func_declarator") 
        	TREE("literal") VAL("(") 
         	NONE CLOSE 
        	TREE("opt") ID("parameter_declaration_list") 
         	NONE CLOSE 
        	TREE("literal") VAL(")") 
         	NONE CLOSE 
        	LIST TREE("rule") LIST TREE("literal") VAL(";") 
            	NONE CLOSE CLOSE 
          	NONE CLOSE 
         	TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
           	TREE("literal") VAL("{") 
            	NONE CLOSE 
           	TREE("wsterminal") ID("inc") CLOSE 
           	ID("decl_or_stat") 
           	TREE("wsterminal") ID("nl") CLOSE 
           	TREE("wsterminal") ID("dec") CLOSE 
           	TREE("literal") VAL("}") 
            	NONE CLOSE CLOSE 
          	NONE CLOSE CLOSE CLOSE 
       	ID("new_style") CLOSE 
      	TREE("rule") LIST ID("func_declarator") 
        	TREE("literal") VAL("(") 
         	NONE CLOSE 
        	TREE("opt") ID("ident_list") 
         	NONE CLOSE 
        	TREE("literal") VAL(")") 
         	NONE CLOSE 
        	TREE("opt") TREE("seq") ID("declaration") 
          	NONE CLOSE 
         	NONE CLOSE 
        	TREE("wsterminal") ID("nl") CLOSE 
        	TREE("literal") VAL("{") 
         	NONE CLOSE 
        	TREE("wsterminal") ID("inc") CLOSE 
        	ID("decl_or_stat") 
        	TREE("wsterminal") ID("nl") CLOSE 
        	TREE("wsterminal") ID("dec") CLOSE 
        	TREE("literal") VAL("}") 
         	NONE CLOSE CLOSE 
       	ID("old_style") CLOSE 
      	TREE("rule") LIST TREE("opt") TREE("list") LIST TREE("rule") LIST ID("declarator") 
             	TREE("opt") LIST TREE("rule") LIST TREE("wsterminal") ID("s") CLOSE 
                 	TREE("literal") VAL("=") 
                  	NONE CLOSE 
                 	TREE("wsterminal") ID("s") CLOSE 
                 	ID("initializer") CLOSE 
                	NONE CLOSE CLOSE 
              	NONE CLOSE CLOSE 
            	NONE CLOSE CLOSE 
          	NONE CLOSE 
         	NONE CLOSE 
        	TREE("literal") VAL(";") 
         	NONE CLOSE CLOSE 
       	ID("var") CLOSE CLOSE CLOSE 
    	ID("decl") CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("for_var_declaration") 
  	LIST TREE("rule") LIST TREE("seq") ID("type_specifier") 
      	NONE CLOSE 
     	TREE("list") LIST TREE("rule") LIST ID("declarator") 
         	TREE("opt") LIST TREE("rule") LIST TREE("wsterminal") ID("s") CLOSE 
             	TREE("literal") VAL("=") 
              	NONE CLOSE 
             	TREE("wsterminal") ID("s") CLOSE 
             	ID("initializer") CLOSE 
            	NONE CLOSE CLOSE 
          	NONE CLOSE CLOSE 
        	NONE CLOSE CLOSE 
      	NONE CLOSE CLOSE 
    	ID("forvardecl") CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("storage_class_specifier") 
  	LIST TREE("rule") LIST TREE("literal") VAL("typedef") 
      	NONE CLOSE CLOSE 
    	ID("typedef") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("extern") 
      	NONE CLOSE CLOSE 
    	ID("extern") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("static") 
      	NONE CLOSE CLOSE 
    	ID("static") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("auto") 
      	NONE CLOSE CLOSE 
    	ID("auto") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("register") 
      	NONE CLOSE CLOSE 
    	ID("register") CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("simple_type_specifier") 
  	LIST TREE("rule") LIST TREE("literal") VAL("char") 
      	NONE CLOSE CLOSE 
    	ID("char") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("short") 
      	NONE CLOSE CLOSE 
    	ID("short") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("int") 
      	NONE CLOSE CLOSE 
    	ID("int") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("long") 
      	NONE CLOSE CLOSE 
    	ID("long") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("signed") 
      	NONE CLOSE CLOSE 
    	ID("signed") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("unsigned") 
      	NONE CLOSE CLOSE 
    	ID("unsigned") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("float") 
      	NONE CLOSE CLOSE 
    	ID("float") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("double") 
      	NONE CLOSE CLOSE 
    	ID("double") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("const") 
      	NONE CLOSE CLOSE 
    	ID("const") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("volatile") 
      	NONE CLOSE CLOSE 
    	ID("volatile") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("void") 
      	NONE CLOSE CLOSE 
    	ID("void") CLOSE 
   	TREE("rule") LIST TREE("identalone") CLOSE CLOSE 
    	ID("typename") CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("type_specifier") 
  	LIST TREE("rule") LIST TREE("literal") VAL("char") 
      	NONE CLOSE CLOSE 
    	ID("char") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("short") 
      	NONE CLOSE CLOSE 
    	ID("short") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("int") 
      	NONE CLOSE CLOSE 
    	ID("int") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("long") 
      	NONE CLOSE CLOSE 
    	ID("long") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("signed") 
      	NONE CLOSE CLOSE 
    	ID("signed") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("unsigned") 
      	NONE CLOSE CLOSE 
    	ID("unsigned") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("float") 
      	NONE CLOSE CLOSE 
    	ID("float") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("double") 
      	NONE CLOSE CLOSE 
    	ID("double") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("const") 
      	NONE CLOSE CLOSE 
    	ID("const") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("volatile") 
      	NONE CLOSE CLOSE 
    	ID("volatile") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("void") 
      	NONE CLOSE CLOSE 
    	ID("void") CLOSE 
   	TREE("rule") LIST ID("struct_or_union_specifier") CLOSE 
    	NONE CLOSE 
   	TREE("rule") LIST ID("enum_specifier") CLOSE 
    	NONE CLOSE 
   	TREE("rule") LIST TREE("identalone") CLOSE CLOSE 
    	ID("typename") CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("struct_or_union_specifier") 
  	LIST TREE("rule") LIST TREE("literal") VAL("struct") 
      	NONE CLOSE 
     	TREE("identalone") CLOSE 
     	TREE("wsterminal") ID("nl") CLOSE 
     	TREE("literal") VAL("{") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("inc") CLOSE 
     	TREE("opt") LIST TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
         	TREE("literal") VAL("...") 
          	NONE CLOSE CLOSE 
        	ID("elipses") CLOSE CLOSE 
      	NONE CLOSE 
     	TREE("seq") LIST TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
         	ID("struct_declaration") CLOSE 
        	NONE CLOSE CLOSE 
      	NONE CLOSE 
     	TREE("wsterminal") ID("dec") CLOSE 
     	TREE("wsterminal") ID("nl") CLOSE 
     	TREE("literal") VAL("}") 
      	NONE CLOSE CLOSE 
    	ID("struct_d") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("struct") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("nl") CLOSE 
     	TREE("literal") VAL("{") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("inc") CLOSE 
     	TREE("opt") LIST TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
         	TREE("literal") VAL("...") 
          	NONE CLOSE CLOSE 
        	ID("elipses") CLOSE CLOSE 
      	NONE CLOSE 
     	TREE("seq") LIST TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
         	ID("struct_declaration") CLOSE 
        	NONE CLOSE CLOSE 
      	NONE CLOSE 
     	TREE("wsterminal") ID("dec") CLOSE 
     	TREE("wsterminal") ID("nl") CLOSE 
     	TREE("literal") VAL("}") 
      	NONE CLOSE CLOSE 
    	ID("struct_n") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("struct") 
      	NONE CLOSE 
     	TREE("identalone") CLOSE CLOSE 
    	ID("struct") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("union") 
      	NONE CLOSE 
     	TREE("identalone") CLOSE 
     	TREE("wsterminal") ID("nl") CLOSE 
     	TREE("literal") VAL("{") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("inc") CLOSE 
     	TREE("opt") LIST TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
         	TREE("literal") VAL("...") 
          	NONE CLOSE CLOSE 
        	ID("elipses") CLOSE CLOSE 
      	NONE CLOSE 
     	TREE("seq") LIST TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
         	ID("struct_declaration") CLOSE 
        	NONE CLOSE CLOSE 
      	NONE CLOSE 
     	TREE("wsterminal") ID("dec") CLOSE 
     	TREE("wsterminal") ID("nl") CLOSE 
     	TREE("literal") VAL("}") 
      	NONE CLOSE CLOSE 
    	ID("union_d") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("union") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("nl") CLOSE 
     	TREE("literal") VAL("{") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("inc") CLOSE 
     	TREE("opt") LIST TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
         	TREE("literal") VAL("...") 
          	NONE CLOSE CLOSE 
        	ID("elipses") CLOSE CLOSE 
      	NONE CLOSE 
     	TREE("seq") LIST TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
         	ID("struct_declaration") CLOSE 
        	NONE CLOSE CLOSE 
      	NONE CLOSE 
     	TREE("wsterminal") ID("dec") CLOSE 
     	TREE("wsterminal") ID("nl") CLOSE 
     	TREE("literal") VAL("}") 
      	NONE CLOSE CLOSE 
    	ID("union_n") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("union") 
      	NONE CLOSE 
     	TREE("identalone") CLOSE CLOSE 
    	ID("union") CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("struct_declaration") 
  	LIST TREE("rule") LIST ID("type_specifier") 
     	ID("struct_declaration") CLOSE 
    	ID("type") CLOSE 
   	TREE("rule") LIST TREE("list") ID("struct_declarator") 
      	NONE CLOSE 
     	TREE("literal") VAL(";") 
      	NONE CLOSE CLOSE 
    	ID("strdec") CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("struct_declarator") 
  	LIST TREE("rule") LIST ID("declarator") 
     	TREE("opt") LIST TREE("rule") LIST TREE("literal") VAL(":") 
          	NONE CLOSE 
         	ID("constant_expr") CLOSE 
        	NONE CLOSE CLOSE 
      	NONE CLOSE CLOSE 
    	ID("record_field") CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("enum_specifier") 
  	LIST TREE("rule") LIST TREE("literal") VAL("enum") 
      	NONE CLOSE 
     	TREE("identalone") CLOSE 
     	TREE("opt") LIST TREE("rule") LIST TREE("literal") VAL("{") 
          	NONE CLOSE 
         	TREE("opt") LIST TREE("rule") LIST TREE("literal") VAL("...") 
              	NONE CLOSE 
             	TREE("literal") VAL(",") 
              	NONE CLOSE CLOSE 
            	ID("elipses") CLOSE CLOSE 
          	NONE CLOSE 
         	TREE("list") ID("enumerator") 
          	NONE CLOSE 
         	TREE("literal") VAL("}") 
          	NONE CLOSE CLOSE 
        	NONE CLOSE CLOSE 
      	NONE CLOSE CLOSE 
    	ID("enum") CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("enumerator") 
  	LIST TREE("rule") LIST TREE("identalone") CLOSE 
     	TREE("opt") LIST TREE("rule") LIST TREE("literal") VAL("=") 
          	NONE CLOSE 
         	ID("constant_expr") CLOSE 
        	NONE CLOSE CLOSE 
      	NONE CLOSE CLOSE 
    	ID("enumerator") CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("func_declarator") 
  	LIST TREE("rule") LIST TREE("literal") VAL("*") 
      	NONE CLOSE 
     	TREE("opt") LIST TREE("rule") LIST TREE("literal") VAL("const") 
          	NONE CLOSE CLOSE 
        	ID("const") CLOSE CLOSE 
      	NONE CLOSE 
     	ID("func_declarator") CLOSE 
    	ID("pointdecl") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("(") 
      	NONE CLOSE 
     	ID("func_declarator") 
     	TREE("literal") VAL(")") 
      	NONE CLOSE CLOSE 
    	NONE CLOSE 
   	TREE("rule") LIST TREE("identalone") CLOSE CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("declarator") 
  	LIST TREE("rule") LIST TREE("literal") VAL("*") 
      	NONE CLOSE 
     	TREE("opt") LIST TREE("rule") LIST TREE("literal") VAL("const") 
          	NONE CLOSE CLOSE 
        	ID("const") CLOSE CLOSE 
      	NONE CLOSE 
     	ID("declarator") CLOSE 
    	ID("pointdecl") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("(") 
      	NONE CLOSE 
     	ID("declarator") 
     	TREE("literal") VAL(")") 
      	NONE CLOSE CLOSE 
    	ID("brackets") CLOSE 
   	TREE("rule") LIST ID("declarator") 
     	TREE("literal") VAL("[") 
      	NONE CLOSE 
     	TREE("opt") ID("constant_expr") 
      	NONE CLOSE 
     	TREE("literal") VAL("]") 
      	NONE CLOSE CLOSE 
    	ID("array") CLOSE 
   	TREE("rule") LIST ID("declarator") 
     	TREE("literal") VAL("(") 
      	NONE CLOSE 
     	TREE("opt") ID("abstract_declaration_list") 
      	NONE CLOSE 
     	TREE("literal") VAL(")") 
      	NONE CLOSE CLOSE 
    	ID("function") CLOSE 
   	TREE("rule") LIST TREE("wsterminal") ID("s") CLOSE 
     	TREE("identalone") CLOSE CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("abstract_declaration_list") 
  	LIST TREE("rule") LIST ID("abstract_declaration") 
     	TREE("opt") LIST TREE("rule") LIST TREE("literal") VAL(",") 
          	NONE CLOSE 
         	LIST TREE("rule") LIST TREE("literal") VAL("...") 
             	NONE CLOSE CLOSE 
           	ID("varargs") CLOSE 
          	TREE("rule") LIST ID("abstract_declaration_list") CLOSE 
           	NONE CLOSE CLOSE CLOSE 
        	NONE CLOSE CLOSE 
      	NONE CLOSE CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("parameter_declaration_list") 
  	LIST TREE("rule") LIST ID("parameter_declaration") 
     	TREE("opt") LIST TREE("rule") LIST TREE("literal") VAL(",") 
          	NONE CLOSE 
         	LIST TREE("rule") LIST TREE("literal") VAL("...") 
             	NONE CLOSE CLOSE 
           	ID("varargs") CLOSE 
          	TREE("rule") LIST ID("parameter_declaration_list") CLOSE 
           	NONE CLOSE CLOSE CLOSE 
        	NONE CLOSE CLOSE 
      	NONE CLOSE CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("ident_list") 
  	LIST TREE("rule") LIST TREE("identalone") CLOSE 
     	TREE("opt") LIST TREE("rule") LIST TREE("literal") VAL(",") 
          	NONE CLOSE 
         	LIST TREE("rule") LIST TREE("literal") VAL("...") 
             	NONE CLOSE CLOSE 
           	ID("varargs") CLOSE 
          	TREE("rule") LIST ID("ident_list") CLOSE 
           	NONE CLOSE CLOSE CLOSE 
        	NONE CLOSE CLOSE 
      	NONE CLOSE CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("parameter_declaration") 
  	LIST TREE("rule") LIST ID("type_specifier") 
     	ID("parameter_declaration") CLOSE 
    	ID("type") CLOSE 
   	TREE("rule") LIST ID("declarator") CLOSE 
    	NONE CLOSE 
   	TREE("rule") LIST ID("abstract_declarator") CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("abstract_declaration") 
  	LIST TREE("rule") LIST ID("type_specifier") 
     	ID("parameter_declaration") CLOSE 
    	ID("type") CLOSE 
   	TREE("rule") LIST ID("abstract_declarator") CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("abstract_declarator") 
  	LIST TREE("rule") LIST TREE("literal") VAL("*") 
      	NONE CLOSE 
     	TREE("opt") LIST TREE("rule") LIST TREE("literal") VAL("const") 
          	NONE CLOSE CLOSE 
        	ID("const") CLOSE CLOSE 
      	NONE CLOSE 
     	ID("abstract_declarator") CLOSE 
    	ID("abs_pointdecl") CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("(") 
      	NONE CLOSE 
     	ID("abstract_declarator") 
     	TREE("literal") VAL(")") 
      	NONE CLOSE CLOSE 
    	ID("abs_brackets") CLOSE 
   	TREE("rule") LIST ID("abstract_declarator") 
     	TREE("literal") VAL("[") 
      	NONE CLOSE 
     	TREE("opt") ID("constant_expr") 
      	NONE CLOSE 
     	TREE("literal") VAL("]") 
      	NONE CLOSE CLOSE 
    	ID("abs_array") CLOSE 
   	TREE("rule") LIST ID("abstract_declarator") 
     	TREE("literal") VAL("(") 
      	NONE CLOSE 
     	ID("parameter_declaration_list") 
     	TREE("literal") VAL(")") 
      	NONE CLOSE CLOSE 
    	ID("abs_func") CLOSE 
   	TREE("rule") NONE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("initializer") 
  	LIST TREE("rule") LIST ID("assignment_expr") CLOSE 
    	NONE CLOSE 
   	TREE("rule") LIST TREE("literal") VAL("{") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("inc") CLOSE 
     	TREE("list") ID("initializer") 
      	NONE CLOSE 
     	TREE("opt") TREE("literal") VAL(",") 
       	NONE CLOSE 
      	NONE CLOSE 
     	TREE("wsterminal") ID("dec") CLOSE 
     	TREE("wsterminal") ID("nl") CLOSE 
     	TREE("literal") VAL("}") 
      	NONE CLOSE CLOSE 
    	ID("initializer") CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("decl_or_stat") 
  	LIST TREE("rule") LIST TREE("opt") LIST TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
         	TREE("literal") VAL("...") 
          	NONE CLOSE CLOSE 
        	ID("elipses") CLOSE CLOSE 
      	NONE CLOSE 
     	TREE("opt") TREE("seq") LIST TREE("rule") LIST ID("statement") CLOSE 
         	NONE CLOSE 
        	TREE("rule") LIST ID("declaration") CLOSE 
         	NONE CLOSE CLOSE 
       	NONE CLOSE 
      	NONE CLOSE CLOSE 
    	NONE CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("statement") 
  	LIST TREE("rule") LIST TREE("wsterminal") ID("dec") CLOSE 
     	TREE("wsterminal") ID("nl") CLOSE 
     	LIST TREE("rule") LIST TREE("identalone") CLOSE CLOSE 
       	ID("l") CLOSE 
      	TREE("rule") LIST TREE("literal") VAL("case") 
         	NONE CLOSE 
        	ID("constant_expr") CLOSE 
       	NONE CLOSE 
      	TREE("rule") LIST TREE("literal") VAL("default") 
         	NONE CLOSE CLOSE 
       	NONE CLOSE CLOSE 
     	TREE("literal") VAL(":") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("inc") CLOSE 
     	ID("statement") CLOSE 
    	ID("label") CLOSE 
   	TREE("rule") LIST TREE("wsterminal") ID("dec") CLOSE 
     	TREE("wsterminal") ID("nl") CLOSE 
     	TREE("literal") VAL("{") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("inc") CLOSE 
     	ID("decl_or_stat") 
     	TREE("wsterminal") ID("dec") CLOSE 
     	TREE("wsterminal") ID("nl") CLOSE 
     	TREE("literal") VAL("}") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("inc") CLOSE CLOSE 
    	ID("brackets") CLOSE 
   	TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
     	ID("macro_ident") 
     	TREE("opt") LIST TREE("rule") LIST TREE("wsterminal") ID("nows") CLOSE 
         	TREE("literal") VAL("(") 
          	NONE CLOSE 
         	TREE("list") LIST TREE("rule") LIST ID("expr") CLOSE 
            	NONE CLOSE 
           	TREE("rule") LIST ID("type_specifier") CLOSE 
            	NONE CLOSE CLOSE 
          	NONE CLOSE 
         	TREE("literal") VAL(")") 
          	NONE CLOSE CLOSE 
        	NONE CLOSE CLOSE 
      	NONE CLOSE CLOSE 
    	ID("macro") CLOSE 
   	TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
     	TREE("opt") ID("expr") 
      	NONE CLOSE 
     	TREE("literal") VAL(";") 
      	NONE CLOSE CLOSE 
    	NONE CLOSE 
   	TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
     	TREE("literal") VAL("if") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL("(") 
      	NONE CLOSE 
     	ID("expr") 
     	TREE("literal") VAL(")") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("inc") CLOSE 
     	ID("statement") 
     	TREE("opt") LIST TREE("rule") LIST TREE("wsterminal") ID("dec") CLOSE 
         	TREE("wsterminal") ID("nl") CLOSE 
         	TREE("literal") VAL("else") 
          	NONE CLOSE 
         	TREE("wsterminal") ID("inc") CLOSE 
         	ID("statement") CLOSE 
        	NONE CLOSE CLOSE 
      	NONE CLOSE 
     	TREE("wsterminal") ID("dec") CLOSE CLOSE 
    	ID("if") CLOSE 
   	TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
     	TREE("literal") VAL("switch") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL("(") 
      	NONE CLOSE 
     	ID("expr") 
     	TREE("literal") VAL(")") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("inc") CLOSE 
     	ID("statement") 
     	TREE("wsterminal") ID("dec") CLOSE CLOSE 
    	ID("switch") CLOSE 
   	TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
     	TREE("literal") VAL("while") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL("(") 
      	NONE CLOSE 
     	ID("expr") 
     	TREE("literal") VAL(")") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("inc") CLOSE 
     	ID("statement") 
     	TREE("wsterminal") ID("dec") CLOSE CLOSE 
    	ID("while") CLOSE 
   	TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
     	TREE("literal") VAL("do") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("inc") CLOSE 
     	ID("statement") 
     	TREE("wsterminal") ID("dec") CLOSE 
     	TREE("wsterminal") ID("nl") CLOSE 
     	TREE("literal") VAL("while") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL("(") 
      	NONE CLOSE 
     	ID("expr") 
     	TREE("literal") VAL(")") 
      	NONE CLOSE 
     	TREE("literal") VAL(";") 
      	NONE CLOSE CLOSE 
    	ID("do") CLOSE 
   	TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
     	TREE("literal") VAL("for") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("s") CLOSE 
     	TREE("literal") VAL("(") 
      	NONE CLOSE 
     	TREE("opt") LIST TREE("rule") LIST ID("for_var_declaration") CLOSE 
        	NONE CLOSE 
       	TREE("rule") LIST ID("expr") CLOSE 
        	NONE CLOSE CLOSE 
      	NONE CLOSE 
     	TREE("literal") VAL(";") 
      	NONE CLOSE 
     	TREE("opt") LIST TREE("rule") LIST TREE("wsterminal") ID("s") CLOSE 
         	ID("expr") CLOSE 
        	NONE CLOSE CLOSE 
      	NONE CLOSE 
     	TREE("literal") VAL(";") 
      	NONE CLOSE 
     	TREE("opt") LIST TREE("rule") LIST TREE("wsterminal") ID("s") CLOSE 
         	ID("expr") CLOSE 
        	NONE CLOSE CLOSE 
      	NONE CLOSE 
     	TREE("literal") VAL(")") 
      	NONE CLOSE 
     	TREE("wsterminal") ID("inc") CLOSE 
     	ID("statement") 
     	TREE("wsterminal") ID("dec") CLOSE CLOSE 
    	ID("for") CLOSE 
   	TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
     	TREE("literal") VAL("goto") 
      	NONE CLOSE 
     	TREE("identalone") CLOSE 
     	TREE("literal") VAL(";") 
      	NONE CLOSE CLOSE 
    	ID("goto") CLOSE 
   	TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
     	TREE("literal") VAL("continue") 
      	NONE CLOSE 
     	TREE("literal") VAL(";") 
      	NONE CLOSE CLOSE 
    	ID("cont") CLOSE 
   	TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
     	TREE("literal") VAL("break") 
      	NONE CLOSE 
     	TREE("literal") VAL(";") 
      	NONE CLOSE CLOSE 
    	ID("break") CLOSE 
   	TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
     	TREE("literal") VAL("return") 
      	NONE CLOSE 
     	TREE("opt") ID("expr") 
      	NONE CLOSE 
     	TREE("literal") VAL(";") 
      	NONE CLOSE CLOSE 
    	ID("ret") CLOSE CLOSE CLOSE 
 	TREE("nt_def") ID("root") 
  	LIST TREE("rule") LIST TREE("opt") TREE("seq") LIST TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
          	ID("declaration") CLOSE 
         	NONE CLOSE 
        	TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
          	TREE("literal") VAL("#define") 
           	NONE CLOSE 
          	ID("macro_ident") 
          	TREE("opt") LIST TREE("rule") LIST TREE("wsterminal") ID("nows") CLOSE 
              	TREE("literal") VAL("(") 
               	NONE CLOSE 
              	TREE("list") TREE("identalone") CLOSE 
               	NONE CLOSE 
              	TREE("literal") VAL(")") 
               	NONE CLOSE CLOSE 
             	NONE CLOSE CLOSE 
           	NONE CLOSE 
          	ID("macro_def") CLOSE 
         	ID("macro") CLOSE 
        	TREE("rule") LIST TREE("wsterminal") ID("nl") CLOSE 
          	TREE("literal") VAL("#include") 
           	NONE CLOSE 
          	LIST TREE("rule") LIST ID("string") CLOSE 
            	NONE CLOSE 
           	TREE("rule") LIST ID("inc_string") CLOSE 
            	NONE CLOSE CLOSE CLOSE 
         	ID("include") CLOSE CLOSE 
       	NONE CLOSE 
      	NONE CLOSE 
     	ID("eof") CLOSE 
    	NONE CLOSE CLOSE CLOSE CLOSE 
    root = tt[0];
}

